### PR TITLE
solve a few bugs

### PR DESCRIPTION
**Pull request by ghislainp**

### CODE REVIEW

**Comment by nojhan** [comment]
Who would have thought this would still be in use… thanks for the update!

**Comment by nojhan** [comment]
BTW, the constant assignement (de)alignment was maybe a bit rude, did you use an automatic code formater?

**Comment by ghislainp** [comment]
Yes sorry, I reformatted the code (autopep8 in sublimtext). It was not my first intent to make a pull request, so I started to reformat before my own debugging (my editor makes non-formatted code annoying to read, so that formatting is nearly compulsory). Do you mean that the code does not read well now ?

**Comment by ghislainp** [comment]
> Who would have thought this would still be in use… thanks for the update!

Do you use another tool now ?

**Comment by nojhan** [comment]
> Do you mean that the code does not read well now ?

No, just one section (where constants are being assigned) have been misaligned. Nothing serious.

> Do you use another tool now ?

No, I just don't use tunnels since a few years (but that may soon change).

**Pull request merged**
